//! Importing a design system's tokens (`PLAN.md` Milestone 48,
//! `docs/tokens.md`): the W3C Design Tokens format, as design tools export
//! it, into the style file's `@theme` block — Milestone 58's token file, so a
//! design system exported from a tool and a theme written by hand are the
//! same artifact, and both spellings (classes and typed styles) read from
//! it.
//!
//! | Token `$type` | Theme namespace |
//! |---|---|
//! | `color` | `--color-…` |
//! | `dimension` in a group named `spacing`/`space` | `--spacing-…` |
//! | `dimension` in a group named `radius`/`radii` | `--radius-…` |
//! | `dimension` in a group named `font-size`/`text` | `--text-…` |
//! | `fontFamily` | `--font-…` |
//! | `fontWeight` | `--font-weight-…` |
//!
//! A token's name is its group path joined by `-` (`brand.blue.500` becomes
//! `--color-brand-blue-500`). An alias (`"{brand.blue.500}"`) becomes a
//! `var(…)` of the aliased token. Other types (shadows, durations,
//! gradients, typography composites) are reported and skipped.
//!
//! **Roles and brand values.** A token is absolute — applied as given —
//! unless it declares `"$extensions": { "rustnative.host": "<role>" }`:
//! then it is a *semantic role* that follows the host's color for that role
//! (`accent`, `on-accent`, `surface`, `on-surface`, `highlight`,
//! `on-highlight`, `border`, `muted`), with its `$value` as the fallback. In
//! the style file such a token carries a `/* host: <role> */` note, which
//! the build turns into `Theme::with_host_role`.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use serde_json::Value;

/// The start of the block `import` writes into a style file.
pub const BEGIN: &str =
    "/* tokens:begin — generated by `rustnative tokens import`; edit the token file instead */";
/// The end of that block.
pub const END: &str = "/* tokens:end */";

/// The roles a token may follow.
pub const HOST_ROLES: [&str; 8] = [
    "accent",
    "on-accent",
    "surface",
    "on-surface",
    "highlight",
    "on-highlight",
    "border",
    "muted",
];

/// What an import produced.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Imported {
    /// The `@theme` block, between [`BEGIN`] and [`END`].
    pub css: String,
    /// Tokens following host roles, as `(token, role)`.
    pub host_roles: Vec<(String, String)>,
    /// Tokens skipped, and why.
    pub warnings: Vec<String>,
}

struct Token {
    path: Vec<String>,
    kind: String,
    value: Value,
    host: Option<String>,
}

fn collect(node: &Value, path: &mut Vec<String>, inherited: Option<&str>, out: &mut Vec<Token>) {
    let Value::Object(map) = node else { return };
    let kind = map.get("$type").and_then(Value::as_str).or(inherited);
    if let Some(value) = map.get("$value") {
        let host = map
            .get("$extensions")
            .and_then(|extensions| extensions.get("rustnative.host"))
            .and_then(Value::as_str)
            .map(str::to_owned);
        out.push(Token {
            path: path.clone(),
            kind: kind.unwrap_or_default().to_owned(),
            value: value.clone(),
            host,
        });
        return;
    }
    for (name, child) in map {
        if name.starts_with('$') {
            continue;
        }
        path.push(name.clone());
        collect(child, path, kind, out);
        path.pop();
    }
}

fn slug(part: &str) -> String {
    part.trim()
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c.to_ascii_lowercase() } else { '-' })
        .collect::<String>()
        .trim_matches('-')
        .to_owned()
}

/// The theme variable name (without `--`) for a token, or why it has none.
fn variable(token: &Token) -> Result<String, String> {
    let path = token.path.iter().map(|part| slug(part)).collect::<Vec<_>>();
    let joined = path.join("-");
    let group = path.first().map(String::as_str).unwrap_or_default();
    let rest = || path[1..].join("-");
    let namespaced = |namespace: &str, prefixes: &[&str]| {
        if prefixes.contains(&group) && path.len() > 1 {
            format!("{namespace}-{}", rest())
        } else {
            format!("{namespace}-{joined}")
        }
    };
    Ok(match token.kind.as_str() {
        "color" => namespaced("color", &["color", "colors"]),
        "dimension" if ["spacing", "space"].contains(&group) => {
            namespaced("spacing", &["spacing", "space"])
        }
        "dimension" if ["radius", "radii"].contains(&group) => {
            namespaced("radius", &["radius", "radii"])
        }
        "dimension" if ["font-size", "font-sizes", "text"].contains(&group) => {
            namespaced("text", &["font-size", "font-sizes", "text"])
        }
        "fontFamily" => namespaced("font", &["font", "fonts", "font-family"]),
        "fontWeight" => namespaced("font-weight", &["font-weight", "font-weights"]),
        other => {
            return Err(format!("{joined}: `{other}` tokens have no theme namespace; skipped"));
        }
    })
}

/// A token's value in CSS, resolving aliases through `names`.
fn css_value(value: &Value, names: &BTreeMap<String, String>) -> Result<String, String> {
    match value {
        Value::String(text) if text.starts_with('{') && text.ends_with('}') => {
            let target = text[1..text.len() - 1].split('.').map(slug).collect::<Vec<_>>().join("-");
            names
                .get(&target)
                .map(|variable| format!("var(--{variable})"))
                .ok_or_else(|| format!("the alias {text} names no token"))
        }
        Value::String(text) => Ok(text.clone()),
        Value::Number(number) => Ok(number.to_string()),
        Value::Array(families) => Ok(families
            .iter()
            .filter_map(Value::as_str)
            .map(
                |family| {
                    if family.contains(' ') { format!("\"{family}\"") } else { family.to_owned() }
                },
            )
            .collect::<Vec<_>>()
            .join(", ")),
        // A dimension written as `{ "value": 4, "unit": "px" }`.
        Value::Object(map) => match (map.get("value"), map.get("unit").and_then(Value::as_str)) {
            (Some(Value::Number(number)), Some(unit)) => Ok(format!("{number}{unit}")),
            _ => Err("an object value that is not a dimension".to_owned()),
        },
        _ => Err("a value of an unsupported shape".to_owned()),
    }
}

/// Imports a W3C Design Tokens document; see the [module
/// documentation](crate::design_tokens).
///
/// # Errors
///
/// The document is not JSON.
///
/// ```
/// let tokens = r##"{
///   "brand": { "$type": "color", "blue": { "$value": "#0f6cbd" } },
///   "color": {
///     "$type": "color",
///     "accent": { "$value": "{brand.blue}", "$extensions": { "rustnative.host": "accent" } }
///   },
///   "spacing": { "$type": "dimension", "md": { "$value": "12px" } }
/// }"##;
/// let imported = framework_style::design_tokens::import(tokens).unwrap();
/// assert!(imported.css.contains("--color-brand-blue: #0f6cbd;"));
/// assert!(imported.css.contains("--color-accent: var(--color-brand-blue); /* host: accent */"));
/// assert!(imported.css.contains("--spacing-md: 12px;"));
/// assert_eq!(imported.host_roles, vec![("color-accent".to_owned(), "accent".to_owned())]);
/// ```
pub fn import(json: &str) -> Result<Imported, String> {
    let document: Value =
        serde_json::from_str(json).map_err(|error| format!("not a token file: {error}"))?;
    let mut tokens = Vec::new();
    collect(&document, &mut Vec::new(), None, &mut tokens);
    let mut imported = Imported::default();
    let mut names = BTreeMap::new();
    let mut declared = Vec::new();
    for token in tokens {
        match variable(&token) {
            Ok(variable) => {
                names.insert(
                    token.path.iter().map(|part| slug(part)).collect::<Vec<_>>().join("-"),
                    variable.clone(),
                );
                declared.push((variable, token));
            }
            Err(warning) => imported.warnings.push(warning),
        }
    }
    let mut css = format!("{BEGIN}\n@theme {{\n");
    for (variable, token) in declared {
        let value = match css_value(&token.value, &names) {
            Ok(value) => value,
            Err(why) => {
                imported.warnings.push(format!("{variable}: {why}; skipped"));
                continue;
            }
        };
        let note = match &token.host {
            Some(role) if HOST_ROLES.contains(&role.as_str()) => {
                imported.host_roles.push((variable.clone(), role.clone()));
                format!(" /* host: {role} */")
            }
            Some(role) => {
                imported
                    .warnings
                    .push(format!("{variable}: `{role}` is not a host role; applied as given"));
                String::new()
            }
            None => String::new(),
        };
        let _ = writeln!(css, "  --{variable}: {value};{note}");
    }
    css.push_str("}\n");
    css.push_str(END);
    css.push('\n');
    imported.css = css;
    Ok(imported)
}

/// `style` with its token block replaced by `block` (or `block` prepended
/// when it has none) — what `rustnative tokens import` writes.
#[must_use]
pub fn replace_block(style: &str, block: &str) -> String {
    match (style.find(BEGIN), style.find(END)) {
        (Some(start), Some(end)) if end > start => {
            let after = &style[end + END.len()..];
            format!("{}{block}{}", &style[..start], after.strip_prefix('\n').unwrap_or(after))
        }
        _ if style.is_empty() => block.to_owned(),
        _ => format!("{block}\n{style}"),
    }
}

/// The `(token, role)` pairs a style file's `/* host: <role> */` notes
/// declare.
#[must_use]
pub fn host_roles(style: &str) -> Vec<(String, String)> {
    style
        .lines()
        .filter_map(|line| {
            let line = line.trim();
            let name = line.strip_prefix("--")?.split(':').next()?.trim();
            let role = line.split("/* host:").nth(1)?.split("*/").next()?.trim();
            HOST_ROLES.contains(&role).then(|| (name.to_owned(), role.to_owned()))
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unsupported_tokens_are_reported_not_lost_silently() {
        let imported =
            import(r#"{ "shadow": { "$type": "shadow", "sm": { "$value": "0 1px 2px black" } } }"#)
                .unwrap();
        assert_eq!(imported.warnings.len(), 1);
        assert!(!imported.css.contains("shadow-sm"));
    }

    #[test]
    fn a_block_is_replaced_in_place_and_host_notes_read_back() {
        let first =
            import(r##"{ "color": { "$type": "color", "ink": { "$value": "#111111" } } }"##)
                .unwrap();
        let style = replace_block("@utility headline { @apply font-bold; }\n", &first.css);
        let second = import(
            r##"{ "color": { "$type": "color", "ink": { "$value": "#222222", "$extensions": { "rustnative.host": "on-surface" } } } }"##,
        )
        .unwrap();
        let style = replace_block(&style, &second.css);
        assert_eq!(style.matches(BEGIN).count(), 1);
        assert!(style.contains("#222222") && !style.contains("#111111"));
        assert!(style.contains("@utility headline"));
        assert_eq!(host_roles(&style), vec![("color-ink".to_owned(), "on-surface".to_owned())]);
    }
}
