//! `rustnative compliance` (`PLAN.md` Milestone 51): compliance evidence
//! generated from the build, into `target/compliance/`.
//!
//! - `sbom.cdx.json`: a `CycloneDX` 1.5 software bill of materials, from
//!   `cargo metadata` (every crate the application links, with its purl
//!   and license).
//! - `licenses.md`: the crates grouped by license.
//! - `dependency-inventory.json`: name, version, source, license.
//! - `privacy-manifest.json` and `permissions.md`: what the application
//!   declares it uses (capabilities, URL schemes, resources, package
//!   capabilities).
//! - `accessibility-report.json`: the outcome of the application's
//!   accessibility tests, when it has them (`tests/accessibility*.rs`).
//! - `traceability.json`: requirement ids mapped to the tests that verify
//!   them, from `// req: ID` annotations in the project's tests.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

use serde_json::{Value, json};

use crate::error::{Error, Result};
use crate::project::Project;

fn io(what: String) -> impl FnOnce(std::io::Error) -> Error {
    move |cause| Error::Io { what, cause }
}

/// A crate in the build.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Component {
    /// Its name.
    pub name: String,
    /// Its version.
    pub version: String,
    /// Its license expression.
    pub license: String,
    /// Where it comes from: `registry`, `path`, or `git`.
    pub source: String,
}

/// The crates `metadata` (`cargo metadata --format-version 1` output)
/// resolves for the workspace, by name.
#[must_use]
pub fn components(metadata: &Value) -> Vec<Component> {
    let mut components: Vec<Component> = metadata["packages"]
        .as_array()
        .into_iter()
        .flatten()
        .map(|package| {
            let source = package["source"].as_str().unwrap_or_default();
            Component {
                name: package["name"].as_str().unwrap_or_default().to_owned(),
                version: package["version"].as_str().unwrap_or_default().to_owned(),
                license: package["license"].as_str().unwrap_or("NOASSERTION").to_owned(),
                source: if source.starts_with("registry+") {
                    "registry".into()
                } else if source.starts_with("git+") {
                    "git".into()
                } else {
                    "path".into()
                },
            }
        })
        .collect();
    components.sort_by(|a, b| (&a.name, &a.version).cmp(&(&b.name, &b.version)));
    components
}

/// The `CycloneDX` 1.5 document.
#[must_use]
pub fn sbom(application: &str, version: &str, components: &[Component]) -> Value {
    json!({
        "bomFormat": "CycloneDX",
        "specVersion": "1.5",
        "version": 1,
        "metadata": {
            "component": { "type": "application", "name": application, "version": version },
            "tools": [{ "vendor": "Rust Native", "name": "rustnative compliance" }],
        },
        "components": components.iter().map(|component| json!({
            "type": "library",
            "name": component.name,
            "version": component.version,
            "purl": format!("pkg:cargo/{}@{}", component.name, component.version),
            "licenses": [{ "expression": component.license }],
        })).collect::<Vec<_>>(),
    })
}

/// `licenses.md`.
#[must_use]
pub fn licenses(components: &[Component]) -> String {
    let mut by_license: BTreeMap<&str, Vec<&Component>> = BTreeMap::new();
    for component in components {
        by_license.entry(component.license.as_str()).or_default().push(component);
    }
    let mut text = String::from(
        "# Licenses\n\nGenerated by `rustnative compliance` from the build's dependency graph.\n",
    );
    for (license, crates) in by_license {
        let _ = write!(text, "\n## {license}\n\n");
        for component in crates {
            let _ = writeln!(text, "- {} {}", component.name, component.version);
        }
    }
    text
}

/// Requirement ids → the tests annotated with them (`// req: X-L3-8`
/// before a test function).
#[must_use]
pub fn traceability(sources: &[(String, String)]) -> BTreeMap<String, Vec<String>> {
    let mut map: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for (file, text) in sources {
        let mut pending: Vec<String> = Vec::new();
        for line in text.lines() {
            let trimmed = line.trim();
            if let Some(ids) = trimmed.strip_prefix("// req:") {
                pending.extend(
                    ids.split(',').map(|id| id.trim().to_owned()).filter(|id| !id.is_empty()),
                );
            } else if let Some(rest) =
                trimmed.strip_prefix("fn ").or_else(|| trimmed.strip_prefix("async fn "))
            {
                let name = rest.split('(').next().unwrap_or_default();
                for id in pending.drain(..) {
                    map.entry(id).or_default().push(format!("{file}::{name}"));
                }
            }
        }
    }
    map
}

fn rust_files(directory: &Path, out: &mut Vec<(String, String)>) {
    let Ok(entries) = std::fs::read_dir(directory) else { return };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            if path.file_name().is_some_and(|name| name != "target") {
                rust_files(&path, out);
            }
        } else if path.extension().is_some_and(|extension| extension == "rs") {
            if let Ok(text) = std::fs::read_to_string(&path) {
                out.push((path.display().to_string(), text));
            }
        }
    }
}

/// Writes the evidence for the project containing `here`.
///
/// # Errors
///
/// `cargo metadata` fails, or a file cannot be written.
pub fn run(here: &Path) -> Result<()> {
    let project = Project::find(here)?;
    let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let output = std::process::Command::new(cargo)
        .current_dir(&project.root)
        .args(["metadata", "--format-version", "1", "--locked"])
        .output()
        .map_err(io("run cargo metadata".into()))?;
    if !output.status.success() {
        return Err(Error::Usage(format!(
            "cargo metadata failed: {}",
            String::from_utf8_lossy(&output.stderr)
        )));
    }
    let metadata: Value =
        serde_json::from_slice(&output.stdout).map_err(|error| Error::Usage(error.to_string()))?;
    let components = components(&metadata);
    let out = project.root.join("target").join("compliance");
    std::fs::create_dir_all(&out).map_err(io(format!("create {}", out.display())))?;
    let write = |name: &str, contents: String| -> Result<()> {
        let path = out.join(name);
        std::fs::write(&path, contents).map_err(io(format!("write {}", path.display())))?;
        println!("compliance: wrote {}", path.display());
        Ok(())
    };
    let app = &project.config.app;
    write(
        "sbom.cdx.json",
        serde_json::to_string_pretty(&sbom(&app.name, &app.version, &components))
            .unwrap_or_default(),
    )?;
    write("licenses.md", licenses(&components))?;
    let inventory: Vec<Value> = components
        .iter()
        .map(|component| json!({ "name": component.name, "version": component.version, "source": component.source, "license": component.license }))
        .collect();
    write(
        "dependency-inventory.json",
        serde_json::to_string_pretty(&inventory).unwrap_or_default(),
    )?;

    let privacy = json!({
        "application": app.id,
        "url_schemes": app.url_schemes,
        "resources": project.config.resources.keys().collect::<Vec<_>>(),
        "package_capabilities": project.config.package.capabilities.clone(),
        "telemetry": "off unless the person consents (docs/telemetry-policy.md)",
    });
    write("privacy-manifest.json", serde_json::to_string_pretty(&privacy).unwrap_or_default())?;
    let mut permissions =
        String::from("# Permissions\n\nWhat the application declares it uses.\n\n");
    for capability in privacy["package_capabilities"].as_array().into_iter().flatten() {
        let _ = writeln!(
            permissions,
            "- package capability `{}`",
            capability.as_str().unwrap_or_default()
        );
    }
    for scheme in &app.url_schemes {
        let _ = writeln!(permissions, "- handles `{scheme}:` links");
    }
    for resource in project.config.resources.keys() {
        let _ = writeln!(permissions, "- the `{resource}` resource");
    }
    write("permissions.md", permissions)?;

    let mut sources = Vec::new();
    rust_files(&project.root.join("tests"), &mut sources);
    rust_files(&project.root.join("src"), &mut sources);
    let accessibility: Vec<&String> = sources
        .iter()
        .map(|(file, _)| file)
        .filter(|file| file.contains("accessibility"))
        .collect();
    let report = if accessibility.is_empty() {
        json!({ "status": "no accessibility tests in this project", "suites": [] })
    } else {
        let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
        let status = std::process::Command::new(cargo)
            .current_dir(&project.root)
            .args(["test", "--quiet", "accessibility"])
            .status();
        json!({ "status": if status.is_ok_and(|status| status.success()) { "passed" } else { "failed" }, "suites": accessibility })
    };
    write("accessibility-report.json", serde_json::to_string_pretty(&report).unwrap_or_default())?;
    write(
        "traceability.json",
        serde_json::to_string_pretty(&traceability(&sources)).unwrap_or_default(),
    )?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn requirements_map_to_the_tests_that_carry_them() {
        let sources = vec![(
            "tests/a.rs".to_owned(),
            "// req: X-L3-8, C68-1\n#[test]\nfn grants_are_enforced() {}\nfn helper() {}\n"
                .to_owned(),
        )];
        let map = traceability(&sources);
        assert_eq!(map["X-L3-8"], ["tests/a.rs::grants_are_enforced"]);
        assert_eq!(map["C68-1"], ["tests/a.rs::grants_are_enforced"]);
        assert!(!map.values().flatten().any(|test| test.ends_with("helper")));
    }

    #[test]
    fn the_sbom_is_cyclonedx_with_purls() {
        let metadata = json!({ "packages": [
            { "name": "serde", "version": "1.0.200", "license": "MIT OR Apache-2.0", "source": "registry+https://github.com/rust-lang/crates.io-index" },
            { "name": "app", "version": "0.1.0", "license": null, "source": null },
        ] });
        let components = components(&metadata);
        let document = sbom("app", "0.1.0", &components);
        assert_eq!(document["specVersion"], "1.5");
        assert_eq!(document["components"][1]["purl"], "pkg:cargo/serde@1.0.200");
        assert!(licenses(&components).contains("## MIT OR Apache-2.0"));
    }
}
