//! The administration surface — generated by `rustnative generate kit
//! admin` (`PLAN.md` Milestone 52, `C57-3`): Milestone 49's generated
//! admin pages over your database, for administrator accounts only. It
//! builds on the auth kit's `Account` (generate that first).

use framework_server::RequestContext;
use framework_server::ServerApp;
use framework_server::admin::Admin;
use framework_server::auth::Policy;
use framework_server::db::Db;
use framework_server::db::schema::Schema;

use super::auth::Account;

/// Accounts that administer the application.
pub struct Admins;

impl Policy<Account> for Admins {
    const NAME: &'static str = "admins";
    fn allows(account: &Account, _: &RequestContext) -> bool {
        account.admin
    }
}

/// Adds `/admin` over every table in `db`, for [`Admins`]. Call it after
/// the auth kit's `routes`, which sets up the sessions it reads.
#[must_use]
pub fn routes(app: ServerApp, db: &Db) -> ServerApp {
    let schema = Schema::of(&db.get()).unwrap_or_default();
    app.admin::<Account, Admins>(Admin::new(db.clone(), schema))
}
