//! A catalogue and a checkout — generated by `rustnative generate kit
//! commerce` (`PLAN.md` Milestone 52, `C57-3`). It sells through the
//! portable `CommerceService` contract, validates every receipt on the
//! server before it records an entitlement, and lists what an account
//! owns. It starts on `FakeStore`; swap in the store your platform bills
//! through when it is available.

use std::sync::Arc;

use framework_core::product::{CommerceService, FakeStore, Product, Receipt};
use framework_server::db::{Db, DbError};
use framework_server::{Json, Path, ServerApp, ServerError, State, get, post};

/// The store and how its receipts are checked.
#[derive(Clone)]
pub struct Store {
    billing: Arc<FakeStore>,
}

impl Store {
    /// A store selling `catalogue`.
    #[must_use]
    pub fn new(catalogue: Vec<Product>) -> Self {
        Self { billing: Arc::new(FakeStore::new(catalogue)) }
    }
}

/// Creates the entitlements table if it is missing.
///
/// # Errors
///
/// The database refused.
pub fn migrate(db: &Db) -> Result<(), DbError> {
    db.get().execute_batch(
        "CREATE TABLE IF NOT EXISTS entitlements (
            buyer TEXT NOT NULL,
            product TEXT NOT NULL,
            transaction_id TEXT NOT NULL UNIQUE
        );",
    )?;
    Ok(())
}

async fn catalogue(State(store): State<Store>) -> Result<Json<Vec<Product>>, ServerError> {
    store
        .billing
        .products()
        .await
        .map(Json)
        .map_err(|unavailable| ServerError::internal(unavailable.reason))
}

async fn checkout(
    Path(buyer): Path<String>,
    State(store): State<Store>,
    State(db): State<Db>,
    Json(product): Json<String>,
) -> Result<Json<Receipt>, ServerError> {
    let receipt = store
        .billing
        .purchase(&product)
        .await
        .map_err(|unavailable| ServerError::bad_request(unavailable.reason))?;
    // Server-side validation: an entitlement is recorded only for a
    // receipt the store itself issued.
    if !store.billing.validate(&receipt) {
        return Err(ServerError::bad_request("The receipt did not validate"));
    }
    let (stored_buyer, stored) = (buyer, receipt.clone());
    db.run(move |connection| {
        connection.execute(
            "INSERT INTO entitlements (buyer, product, transaction_id) VALUES (?1, ?2, ?3)",
            (&stored_buyer, &stored.product, &stored.transaction),
        )?;
        Ok(())
    })
    .await
    .map_err(ServerError::from)?;
    Ok(Json(receipt))
}

async fn owned(
    Path(buyer): Path<String>,
    State(db): State<Db>,
) -> Result<Json<Vec<String>>, ServerError> {
    let connection = db.get();
    let mut statement = connection
        .prepare("SELECT product FROM entitlements WHERE buyer = ?1 ORDER BY rowid")
        .map_err(|error| ServerError::internal(error.to_string()))?;
    let products = statement
        .query_map([&buyer], |row| row.get(0))
        .and_then(Iterator::collect)
        .map_err(|error| ServerError::internal(error.to_string()))?;
    Ok(Json(products))
}

/// Adds the store's routes to `app`. Put `checkout` and `owned` behind
/// your sign-in (`.signed_in::<Account>()` with the auth kit) before
/// shipping: they are public here only so the kit works on its own.
#[must_use]
pub fn routes(app: ServerApp, db: &Db, store: Store) -> ServerApp {
    app.state(db.clone())
        .state(store)
        .route("/store/products", get(catalogue).public())
        .route("/store/:buyer/checkout", post(checkout).public())
        .route("/store/:buyer/owned", get(owned).public())
}
