//! Bindings generated from an [`Idl`] — never written by hand per language
//! (`PLAN.md` Milestone 40, concept `C66`).
//!
//! - [`c`]: the C header a host includes;
//! - [`csharp`]: P/Invoke bindings (C# 5, so the .NET Framework compiler
//!   every Windows machine has can build them) with an `IDisposable`
//!   wrapper per service;
//! - [`rust`]: the implementation side — a trait per service, its events,
//!   and an `export_<library>!` macro that writes the `extern "C"` shims
//!   over [`crate::runtime`] (handle table, panic containment, thread
//!   check).
//!
//! The C ABI they share: every function returns an `int32_t` status (see
//! [`crate::runtime::status`]) and writes its result through a final
//! out-pointer; a service instance is a `uint64_t` handle the host frees;
//! a `string` argument is borrowed for the call and a returned one is the
//! host's to free with `<library>_string_free`.

use std::fmt::Write as _;

use crate::idl::{Idl, Param, Receiver, Service, Threading, Type};

fn pascal(name: &str) -> String {
    name.split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            chars
                .next()
                .map(|first| first.to_ascii_uppercase().to_string() + chars.as_str())
                .unwrap_or_default()
        })
        .collect()
}

/// Whether every method of `service` is owner-affine.
fn owner_only(service: &Service) -> bool {
    service.methods.iter().all(|method| method.threading == Threading::Owner)
}

fn symbol(idl: &Idl, service: &Service, name: &str) -> String {
    format!("{}_{}_{name}", idl.library, service.name)
}

// ---------------------------------------------------------------------------
// C
// ---------------------------------------------------------------------------

const fn c_type(ty: Type) -> &'static str {
    match ty {
        Type::Bool => "uint8_t",
        Type::I32 => "int32_t",
        Type::U32 => "uint32_t",
        Type::I64 => "int64_t",
        Type::U64 => "uint64_t",
        Type::F64 => "double",
        Type::String => "const char*",
    }
}

const fn c_out(ty: Type) -> &'static str {
    match ty {
        Type::String => "char**",
        Type::Bool => "uint8_t*",
        Type::I32 => "int32_t*",
        Type::U32 => "uint32_t*",
        Type::I64 => "int64_t*",
        Type::U64 => "uint64_t*",
        Type::F64 => "double*",
    }
}

fn c_params(params: &[Param]) -> Vec<String> {
    params.iter().map(|param| format!("{} {}", c_type(param.ty), param.name)).collect()
}

fn c_doc(out: &mut String, doc: &[String], indent: &str) {
    for line in doc {
        let _ = writeln!(out, "{indent}/* {line} */");
    }
}

/// The C header.
#[must_use]
pub fn c(idl: &Idl) -> String {
    let library = &idl.library;
    let guard = format!("{}_H", library.to_ascii_uppercase());
    let upper = library.to_ascii_uppercase();
    let mut out = String::new();
    let _ =
        writeln!(out, "/* Generated by framework-interop from `{library}.ril`. Do not edit. */");
    let _ = writeln!(out, "#ifndef {guard}\n#define {guard}\n\n#include <stdint.h>\n");
    let _ = writeln!(out, "#ifdef __cplusplus\nextern \"C\" {{\n#endif\n");
    for (name, value) in [
        ("OK", 0),
        ("PANICKED", 1),
        ("WRONG_THREAD", 2),
        ("INVALID_HANDLE", 3),
        ("INVALID_ARGUMENT", 4),
        ("BUSY", 5),
    ] {
        let _ = writeln!(out, "#define {upper}_{name} {value}");
    }
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "/* This thread's last failure message; valid until its next failing call. */"
    );
    let _ = writeln!(out, "const char* {library}_last_error(void);");
    let _ = writeln!(out, "/* Frees a string the library returned. */");
    let _ = writeln!(out, "void {library}_string_free(char* value);\n");
    for service in &idl.services {
        c_doc(&mut out, &service.doc, "");
        let handle = format!("{library}_{}", service.name);
        let _ = writeln!(out, "typedef uint64_t {handle};\n");
        let mut params = c_params(&service.constructor);
        params.push(format!("{handle}* out"));
        let _ = writeln!(out, "int32_t {}({});", symbol(idl, service, "new"), params.join(", "));
        let _ = writeln!(out, "int32_t {}({handle} self);", symbol(idl, service, "free"));
        for method in &service.methods {
            c_doc(&mut out, &method.doc, "");
            let mut params = vec![format!("{handle} self")];
            params.extend(c_params(&method.params));
            if let Some(ty) = method.returns {
                params.push(format!("{} out", c_out(ty)));
            }
            let threading = match method.threading {
                Threading::Owner => "owner thread",
                Threading::Any => "any thread",
            };
            let _ = writeln!(out, "/* [{threading}] */");
            let _ = writeln!(
                out,
                "int32_t {}({});",
                symbol(idl, service, &method.name),
                params.join(", ")
            );
        }
        for event in &service.events {
            c_doc(&mut out, &event.doc, "");
            let mut params = vec!["void* context".to_owned()];
            params.extend(c_params(&event.params));
            let callback = format!("{}_fn", symbol(idl, service, &event.name));
            let _ = writeln!(out, "typedef void (*{callback})({});", params.join(", "));
            let _ = writeln!(
                out,
                "int32_t {}({handle} self, {callback} callback, void* context);",
                symbol(idl, service, &format!("on_{}", event.name))
            );
        }
        let _ = writeln!(out);
    }
    let _ = writeln!(out, "#ifdef __cplusplus\n}}\n#endif\n\n#endif");
    out
}

// ---------------------------------------------------------------------------
// C#
// ---------------------------------------------------------------------------

const fn cs_type(ty: Type) -> &'static str {
    match ty {
        Type::Bool => "bool",
        Type::I32 => "int",
        Type::U32 => "uint",
        Type::I64 => "long",
        Type::U64 => "ulong",
        Type::F64 => "double",
        Type::String => "string",
    }
}

/// The P/Invoke type of an argument.
const fn cs_native(ty: Type) -> &'static str {
    match ty {
        Type::Bool => "byte",
        Type::String => "byte[]",
        other => cs_type(other),
    }
}

/// The P/Invoke type of a result or callback argument.
const fn cs_native_out(ty: Type) -> &'static str {
    match ty {
        Type::Bool => "byte",
        Type::String => "IntPtr",
        other => cs_type(other),
    }
}

fn cs_argument(param: &Param) -> String {
    match param.ty {
        Type::Bool => format!("(byte)({} ? 1 : 0)", param.name),
        Type::String => format!("Native.Utf8Z({})", param.name),
        _ => param.name.clone(),
    }
}

fn cs_doc(out: &mut String, doc: &[String], indent: &str) {
    if doc.is_empty() {
        return;
    }
    let _ = writeln!(out, "{indent}/// <summary>{}</summary>", doc.join(" "));
}

/// The C# bindings.
#[must_use]
pub fn csharp(idl: &Idl) -> String {
    let library = &idl.library;
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by framework-interop from `{library}.ril`. Do not edit.");
    let _ = writeln!(
        out,
        "using System;\nusing System.Collections.Generic;\nusing System.Runtime.InteropServices;\nusing System.Text;\n"
    );
    let _ = writeln!(out, "namespace {}.Interop\n{{", pascal(library));
    let _ = writeln!(
        out,
        "    /// <summary>A failure the library reported, with its status code.</summary>\n    public sealed class InteropException : Exception\n    {{\n        private readonly int status;\n        public InteropException(int status, string message) : base(message) {{ this.status = status; }}\n        public int Status {{ get {{ return status; }} }}\n    }}\n"
    );
    // Native declarations.
    let _ = writeln!(
        out,
        "    internal static class Native\n    {{\n        private const string Library = \"{library}\";\n"
    );
    let import = "        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]";
    let _ =
        writeln!(out, "{import}\n        internal static extern IntPtr {library}_last_error();");
    let _ = writeln!(
        out,
        "{import}\n        internal static extern void {library}_string_free(IntPtr value);"
    );
    for service in &idl.services {
        let mut params: Vec<String> = service
            .constructor
            .iter()
            .map(|param| format!("{} {}", cs_native(param.ty), param.name))
            .collect();
        params.push("out ulong handle".to_owned());
        let _ = writeln!(
            out,
            "{import}\n        internal static extern int {}({});",
            symbol(idl, service, "new"),
            params.join(", ")
        );
        let _ = writeln!(
            out,
            "{import}\n        internal static extern int {}(ulong self);",
            symbol(idl, service, "free")
        );
        for method in &service.methods {
            let mut params = vec!["ulong self".to_owned()];
            params.extend(
                method.params.iter().map(|param| format!("{} {}", cs_native(param.ty), param.name)),
            );
            if let Some(ty) = method.returns {
                params.push(format!("out {} result", cs_native_out(ty)));
            }
            let _ = writeln!(
                out,
                "{import}\n        internal static extern int {}({});",
                symbol(idl, service, &method.name),
                params.join(", ")
            );
        }
        for event in &service.events {
            let _ = writeln!(
                out,
                "{import}\n        internal static extern int {}(ulong self, {}{}Fn callback, IntPtr context);",
                symbol(idl, service, &format!("on_{}", event.name)),
                service.name,
                pascal(&event.name)
            );
        }
    }
    let _ = writeln!(
        out,
        r#"
        internal static void Check(int status)
        {{
            if (status != 0) throw new InteropException(status, Utf8({library}_last_error()));
        }}

        internal static byte[] Utf8Z(string value)
        {{
            if (value == null) throw new ArgumentNullException("value");
            byte[] bytes = Encoding.UTF8.GetBytes(value);
            byte[] terminated = new byte[bytes.Length + 1];
            Array.Copy(bytes, terminated, bytes.Length);
            return terminated;
        }}

        internal static string Utf8(IntPtr pointer)
        {{
            if (pointer == IntPtr.Zero) return "";
            int length = 0;
            while (Marshal.ReadByte(pointer, length) != 0) length++;
            byte[] bytes = new byte[length];
            Marshal.Copy(pointer, bytes, 0, length);
            return Encoding.UTF8.GetString(bytes);
        }}

        internal static string TakeUtf8(IntPtr pointer)
        {{
            try {{ return Utf8(pointer); }} finally {{ {library}_string_free(pointer); }}
        }}
    }}
"#
    );
    for service in &idl.services {
        csharp_class(&mut out, idl, service);
    }
    let _ = writeln!(out, "}}");
    out
}

// ---------------------------------------------------------------------------
// Rust (the implementation side)
// ---------------------------------------------------------------------------

const fn rust_type(ty: Type) -> &'static str {
    match ty {
        Type::Bool => "bool",
        Type::I32 => "i32",
        Type::U32 => "u32",
        Type::I64 => "i64",
        Type::U64 => "u64",
        Type::F64 => "f64",
        Type::String => "&str",
    }
}

const fn rust_ffi(ty: Type) -> &'static str {
    match ty {
        Type::Bool => "u8",
        Type::String => "*const ::core::ffi::c_char",
        other => rust_type(other),
    }
}

const fn rust_ffi_out(ty: Type) -> &'static str {
    match ty {
        Type::Bool => "*mut u8",
        Type::I32 => "*mut i32",
        Type::U32 => "*mut u32",
        Type::I64 => "*mut i64",
        Type::U64 => "*mut u64",
        Type::F64 => "*mut f64",
        Type::String => "*mut *mut ::core::ffi::c_char",
    }
}

const fn rust_return(ty: Type) -> &'static str {
    match ty {
        Type::String => "::std::string::String",
        other => rust_type(other),
    }
}

/// Converts FFI arguments to Rust ones at the top of a shim.
fn rust_prologue(params: &[Param]) -> String {
    let mut out = String::new();
    for param in params {
        let name = &param.name;
        match param.ty {
            Type::String => {
                let _ = writeln!(
                    out,
                    "                // SAFETY: the header's contract: a `string` argument is a NUL-terminated\n                // UTF-8 string valid for the call.\n                let {name} = unsafe {{ ::framework_interop::runtime::borrow_str({name}, \"{name}\") }}?;"
                );
            }
            Type::Bool => {
                let _ = writeln!(out, "                let {name} = {name} != 0;");
            }
            _ => {}
        }
    }
    out
}

fn rust_doc(out: &mut String, doc: &[String], indent: &str) {
    for line in doc {
        let _ = writeln!(out, "{indent}/// {line}");
    }
}

/// The implementation side: include it in the crate that implements the
/// library (`include!(concat!(env!("OUT_DIR"), "/<library>.rs"))`),
/// implement each service's trait, and call `export_<library>!` with the
/// implementing types in declaration order.
#[must_use]
pub fn rust(idl: &Idl) -> String {
    let library = &idl.library;
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by framework-interop from `{library}.ril`. Do not edit.\n");
    for service in &idl.services {
        let name = &service.name;
        // Events.
        for event in &service.events {
            let mut params = vec!["*mut ::core::ffi::c_void".to_owned()];
            params.extend(event.params.iter().map(|param| rust_ffi(param.ty).to_owned()));
            let _ = writeln!(
                out,
                "/// The host's callback for `{name}`'s `{}` event.\npub type {name}{}Fn = unsafe extern \"C\" fn({});\n",
                event.name,
                pascal(&event.name),
                params.join(", ")
            );
        }
        let _ = writeln!(
            out,
            "/// The events a `{name}` raises, with the callbacks the host registered.\n#[derive(Default)]\npub struct {name}Events {{"
        );
        for event in &service.events {
            let _ = writeln!(
                out,
                "    {}: ::std::vec::Vec<({name}{}Fn, usize)>,",
                event.name,
                pascal(&event.name)
            );
        }
        let _ = writeln!(out, "}}\n\nimpl {name}Events {{");
        for event in &service.events {
            rust_doc(&mut out, &event.doc, "    ");
            let params: Vec<String> = event
                .params
                .iter()
                .map(|param| format!("{}: {}", param.name, rust_type(param.ty)))
                .collect();
            let mut conversions = String::new();
            let mut arguments = vec!["*context as *mut ::core::ffi::c_void".to_owned()];
            for param in &event.params {
                match param.ty {
                    Type::String => {
                        let _ = writeln!(
                            conversions,
                            "        let {0} = ::std::ffi::CString::new({0}.replace('\\0', \" \")).unwrap_or_default();",
                            param.name
                        );
                        arguments.push(format!("{}.as_ptr()", param.name));
                    }
                    Type::Bool => arguments.push(format!("u8::from({})", param.name)),
                    _ => arguments.push(param.name.clone()),
                }
            }
            let _ = writeln!(
                out,
                "    /// Raises `{event}`: calls every registered callback, on this thread.\n    pub fn {event}(&self{comma}{params}) {{\n{conversions}        for (callback, context) in &self.{event} {{\n            // SAFETY: the host registered `callback` with `context` for this event,\n            // and its contract keeps both valid until the instance is freed.\n            unsafe {{ callback({arguments}) }};\n        }}\n    }}",
                event = event.name,
                comma = if params.is_empty() { "" } else { ", " },
                params = params.join(", "),
                arguments = arguments.join(", ")
            );
        }
        let _ = writeln!(out, "}}\n");
        // The trait.
        rust_doc(&mut out, &service.doc, "");
        // A service reachable from any thread must be `Send`; one whose every
        // method is owner-affine need not be (it may hold a component tree).
        let bound = if owner_only(service) { "'static" } else { "Send + 'static" };
        let _ = writeln!(out, "pub trait {name}: {bound} {{");
        let params: Vec<String> = service
            .constructor
            .iter()
            .map(|param| format!("{}: {}", param.name, rust_type(param.ty)))
            .collect();
        let _ = writeln!(
            out,
            "    /// Creates an instance.\n    fn new({}) -> Self\n    where\n        Self: Sized;",
            params.join(", ")
        );
        for method in &service.methods {
            rust_doc(&mut out, &method.doc, "    ");
            let receiver = match method.receiver {
                Receiver::Shared => "&self",
                Receiver::Exclusive => "&mut self",
            };
            let mut params: Vec<String> = method
                .params
                .iter()
                .map(|param| format!("{}: {}", param.name, rust_type(param.ty)))
                .collect();
            if method.receiver == Receiver::Exclusive {
                params.push(format!("events: &{name}Events"));
            }
            let returns =
                method.returns.map(|ty| format!(" -> {}", rust_return(ty))).unwrap_or_default();
            let comma = if params.is_empty() { "" } else { ", " };
            let _ = writeln!(
                out,
                "    fn {}({receiver}{comma}{}){returns};",
                method.name,
                params.join(", ")
            );
        }
        let _ = writeln!(out, "}}\n");
        let _ = writeln!(
            out,
            "#[doc(hidden)]\npub struct {name}Instance<T> {{\n    pub value: T,\n    pub events: {name}Events,\n}}\n"
        );
    }
    // The export macro.
    let types: Vec<String> = idl
        .services
        .iter()
        .map(|service| format!("${}:ty", service.name.to_ascii_lowercase()))
        .collect();
    let _ = writeln!(
        out,
        "/// Exports the C interface of `{library}.ril`, implemented by the given\n/// types (one per service, in declaration order).\n#[allow(unused_macros)]\nmacro_rules! export_{library} {{\n    ({} $(,)?) => {{",
        types.join(", ")
    );
    let attributes = "        #[unsafe(no_mangle)]\n        #[allow(non_snake_case, clippy::must_use_candidate, clippy::missing_safety_doc)]";
    let _ = writeln!(
        out,
        "{attributes}\n        pub extern \"C\" fn {library}_last_error() -> *const ::core::ffi::c_char {{\n            ::framework_interop::runtime::last_error()\n        }}\n\n{attributes}\n        pub unsafe extern \"C\" fn {library}_string_free(value: *mut ::core::ffi::c_char) {{\n            // SAFETY: the header's contract: `value` is null or a string this library returned.\n            unsafe {{ ::framework_interop::runtime::free_string(value) }}\n        }}\n"
    );
    for service in &idl.services {
        rust_service_shims(&mut out, idl, service, attributes);
    }
    let _ = writeln!(out, "    }};\n}}");
    out
}

fn csharp_class(out: &mut String, idl: &Idl, service: &Service) {
    for event in &service.events {
        let mut params = vec!["IntPtr context".to_owned()];
        params.extend(
            event.params.iter().map(|param| format!("{} {}", cs_native_out(param.ty), param.name)),
        );
        let _ = writeln!(
            out,
            "    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]\n    internal delegate void {}{}Fn({});\n",
            service.name,
            pascal(&event.name),
            params.join(", ")
        );
    }
    cs_doc(out, &service.doc, "    ");
    let name = &service.name;
    let _ = writeln!(out, "    public sealed class {name} : IDisposable\n    {{");
    let _ = writeln!(out, "        private ulong handle;");
    let _ =
        writeln!(out, "        // Delegates handed to native code, kept alive with the instance.");
    let _ = writeln!(
        out,
        "        private readonly List<Delegate> callbacks = new List<Delegate>();\n"
    );
    let params: Vec<String> = service
        .constructor
        .iter()
        .map(|param| format!("{} {}", cs_type(param.ty), param.name))
        .collect();
    let mut arguments: Vec<String> = service.constructor.iter().map(cs_argument).collect();
    arguments.push("out handle".to_owned());
    let _ = writeln!(
        out,
        "        public {name}({})\n        {{\n            Native.Check(Native.{}({}));\n        }}\n",
        params.join(", "),
        symbol(idl, service, "new"),
        arguments.join(", ")
    );
    for method in &service.methods {
        cs_doc(out, &method.doc, "        ");
        let params: Vec<String> = method
            .params
            .iter()
            .map(|param| format!("{} {}", cs_type(param.ty), param.name))
            .collect();
        let mut arguments = vec!["handle".to_owned()];
        arguments.extend(method.params.iter().map(cs_argument));
        let call = |arguments: &[String]| {
            format!("Native.{}({})", symbol(idl, service, &method.name), arguments.join(", "))
        };
        let body = match method.returns {
            None => format!("            Native.Check({});", call(&arguments)),
            Some(ty) => {
                arguments.push("out result".to_owned());
                let convert = match ty {
                    Type::Bool => "result != 0".to_owned(),
                    Type::String => "Native.TakeUtf8(result)".to_owned(),
                    _ => "result".to_owned(),
                };
                format!(
                    "            {} result;\n            Native.Check({});\n            return {convert};",
                    cs_native_out(ty),
                    call(&arguments)
                )
            }
        };
        let returns = method.returns.map_or("void", cs_type);
        let _ = writeln!(
            out,
            "        public {returns} {}({})\n        {{\n{body}\n        }}\n",
            pascal(&method.name),
            params.join(", ")
        );
    }
    for event in &service.events {
        let delegate = format!("{name}{}Fn", pascal(&event.name));
        let action = if event.params.is_empty() {
            "Action".to_owned()
        } else {
            format!(
                "Action<{}>",
                event.params.iter().map(|param| cs_type(param.ty)).collect::<Vec<_>>().join(", ")
            )
        };
        let lambda_params: Vec<String> = std::iter::once("context".to_owned())
            .chain(event.params.iter().map(|param| param.name.clone()))
            .collect();
        let forwarded: Vec<String> = event
            .params
            .iter()
            .map(|param| match param.ty {
                Type::Bool => format!("{} != 0", param.name),
                Type::String => format!("Native.Utf8({})", param.name),
                _ => param.name.clone(),
            })
            .collect();
        cs_doc(out, &event.doc, "        ");
        let _ = writeln!(
            out,
            "        public void On{}({action} handler)\n        {{\n            {delegate} callback = ({}) => handler({});\n            callbacks.Add(callback);\n            Native.Check(Native.{}(handle, callback, IntPtr.Zero));\n        }}\n",
            pascal(&event.name),
            lambda_params.join(", "),
            forwarded.join(", "),
            symbol(idl, service, &format!("on_{}", event.name))
        );
    }
    let _ = writeln!(
        out,
        "        public void Dispose()\n        {{\n            if (handle == 0) return;\n            Native.Check(Native.{}(handle));\n            handle = 0;\n        }}\n    }}\n",
        symbol(idl, service, "free")
    );
}

fn rust_service_shims(out: &mut String, idl: &Idl, service: &Service, attributes: &str) {
    let library = &idl.library;
    let name = &service.name;
    let ty = format!("${}", name.to_ascii_lowercase());
    let table = format!("{}_{}_INSTANCES", library.to_ascii_uppercase(), name.to_ascii_uppercase());
    let kind = if owner_only(service) { "OwnerTable" } else { "HandleTable" };
    let _ = writeln!(
        out,
        "        static {table}: ::framework_interop::runtime::{kind}<{name}Instance<{ty}>> =\n            ::framework_interop::runtime::{kind}::new();\n"
    );
    // Constructor.
    let mut params: Vec<String> = service
        .constructor
        .iter()
        .map(|param| format!("{}: {}", param.name, rust_ffi(param.ty)))
        .collect();
    params.push("out: *mut u64".to_owned());
    let arguments: Vec<&str> =
        service.constructor.iter().map(|param| param.name.as_str()).collect();
    let _ = writeln!(
        out,
        "{attributes}\n        pub unsafe extern \"C\" fn {}({}) -> i32 {{\n            ::framework_interop::runtime::guard(|| {{\n{}                let value = <{ty} as {name}>::new({});\n                let handle = {table}.insert({name}Instance {{ value, events: {name}Events::default() }});\n                // SAFETY: the header's contract: `out` is valid for one handle.\n                unsafe {{ ::framework_interop::runtime::write(out, handle) }}\n            }})\n        }}\n",
        symbol(idl, service, "new"),
        params.join(", "),
        rust_prologue(&service.constructor),
        arguments.join(", ")
    );
    // Free.
    let _ = writeln!(
        out,
        "{attributes}\n        pub extern \"C\" fn {}(this: u64) -> i32 {{\n            ::framework_interop::runtime::guard(|| {table}.remove(this))\n        }}\n",
        symbol(idl, service, "free")
    );
    // Methods.
    for method in &service.methods {
        let mut params = vec!["this: u64".to_owned()];
        params.extend(
            method.params.iter().map(|param| format!("{}: {}", param.name, rust_ffi(param.ty))),
        );
        if let Some(ty) = method.returns {
            params.push(format!("out: {}", rust_ffi_out(ty)));
        }
        let affinity = match method.threading {
            Threading::Owner => "Owner",
            Threading::Any => "Any",
        };
        let mut arguments: Vec<String> =
            method.params.iter().map(|param| param.name.clone()).collect();
        if method.receiver == Receiver::Exclusive {
            arguments.push("events".to_owned());
        }
        let call = format!(
            "{table}.with(this, ::framework_interop::runtime::Affinity::{affinity}, |instance| {{\n                    let {name}Instance {{ value, events }} = instance;\n                    let _ = &events;\n                    {name}::{}(value, {})\n                }})?",
            method.name,
            arguments.join(", ")
        );
        let finish = match method.returns {
            None => format!("                {call};\n                Ok(())"),
            Some(ty) => {
                let convert = match ty {
                    Type::Bool => "u8::from(result)",
                    Type::String => "::framework_interop::runtime::owned_string(&result)",
                    _ => "result",
                };
                format!(
                    "                let result = {call};\n                // SAFETY: the header's contract: `out` is valid for one result.\n                unsafe {{ ::framework_interop::runtime::write(out, {convert}) }}"
                )
            }
        };
        let _ = writeln!(
            out,
            "{attributes}\n        pub unsafe extern \"C\" fn {}({}) -> i32 {{\n            ::framework_interop::runtime::guard(|| {{\n{}{finish}\n            }})\n        }}\n",
            symbol(idl, service, &method.name),
            params.join(", "),
            rust_prologue(&method.params)
        );
    }
    // Event registration.
    for event in &service.events {
        let _ = writeln!(
            out,
            "{attributes}\n        pub extern \"C\" fn {}(this: u64, callback: ::core::option::Option<{name}{}Fn>, context: *mut ::core::ffi::c_void) -> i32 {{\n            ::framework_interop::runtime::guard(|| {{\n                let callback = callback.ok_or_else(|| {{\n                    ::framework_interop::runtime::fail(::framework_interop::runtime::status::INVALID_ARGUMENT, \"the callback is null\")\n                }})?;\n                let context = context as usize;\n                {table}.with(this, ::framework_interop::runtime::Affinity::Owner, |instance| {{\n                    instance.events.{}.push((callback, context));\n                }})\n            }})\n        }}\n",
            symbol(idl, service, &format!("on_{}", event.name)),
            pascal(&event.name),
            event.name
        );
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::idl::parse_idl;

    const COUNTER: &str = "library counter;\nservice Counter {\n    new(start: u32);\n    fn increment(&mut self) -> u32;\n    fn name(&self) -> string;\n    fn rename(&mut self, name: string);\n    event changed(value: u32);\n}\n";

    #[test]
    fn the_c_header_declares_the_abi() {
        let header = c(&parse_idl(COUNTER).unwrap());
        assert!(
            header.contains("int32_t counter_Counter_new(uint32_t start, counter_Counter* out);"),
            "{header}"
        );
        assert!(
            header.contains("int32_t counter_Counter_name(counter_Counter self, char** out);"),
            "{header}"
        );
        assert!(
            header.contains(
                "typedef void (*counter_Counter_changed_fn)(void* context, uint32_t value);"
            ),
            "{header}"
        );
        assert!(header.contains("void counter_string_free(char* value);"), "{header}");
    }

    #[test]
    fn csharp_wraps_each_service() {
        let bindings = csharp(&parse_idl(COUNTER).unwrap());
        assert!(bindings.contains("public sealed class Counter : IDisposable"), "{bindings}");
        assert!(bindings.contains("public uint Increment()"), "{bindings}");
        assert!(bindings.contains("public void OnChanged(Action<uint> handler)"), "{bindings}");
    }

    #[test]
    fn rust_writes_a_trait_and_an_export_macro() {
        let shims = rust(&parse_idl(COUNTER).unwrap());
        assert!(shims.contains("pub trait Counter: 'static {"), "{shims}");
        assert!(shims.contains("runtime::OwnerTable<CounterInstance<$counter>>"), "{shims}");
        assert!(
            shims.contains("fn increment(&mut self, events: &CounterEvents) -> u32;"),
            "{shims}"
        );
        assert!(shims.contains("macro_rules! export_counter"), "{shims}");
    }
}
