mod support;

// Generated by `rustnative inspect to-test` from a recording (`PLAN.md`
// Milestone 44, `C61`): replays the recorded input and service responses on
// the headless backend and checks the state it ends in.

#[test]
fn replays_the_recorded_greeting() {
    use framework_core::Component as _;

    let recording: framework_core::inspect::Recording = serde_json::from_str(
        r#"{
  "version": 1,
  "inputs": [
    {
      "at_ms": 0,
      "event": {
        "event": "focus_gained",
        "node": {
          "component": "",
          "key": "name"
        }
      }
    },
    {
      "at_ms": 0,
      "event": {
        "event": "text_changed",
        "node": {
          "component": "",
          "key": "name"
        },
        "value": "Ada"
      }
    },
    {
      "at_ms": 250,
      "event": {
        "event": "focus_lost",
        "node": {
          "component": "",
          "key": "name"
        }
      }
    },
    {
      "at_ms": 250,
      "event": {
        "event": "focus_gained",
        "node": {
          "component": "",
          "key": "secret"
        }
      }
    },
    {
      "at_ms": 250,
      "event": {
        "event": "focus_lost",
        "node": {
          "component": "",
          "key": "secret"
        }
      }
    },
    {
      "at_ms": 250,
      "event": {
        "event": "focus_gained",
        "node": {
          "component": "",
          "key": "load"
        }
      }
    },
    {
      "at_ms": 250,
      "event": {
        "event": "click",
        "node": {
          "component": "",
          "key": "load"
        }
      }
    }
  ],
  "http": [
    {
      "method": "GET",
      "url": "https://api.test/greet?name=Ada",
      "status": 200,
      "headers": [],
      "body": "Hello, Ada",
      "error": null
    }
  ],
  "redacted": [
    "secret"
  ],
  "final_state": {
    "": {
      "greeting": "Hello, Ada",
      "loads": 1,
      "name": "Ada"
    }
  }
}"#,
    )
    .expect("the recording is valid");
    let mut app = framework_headless::HeadlessApp::launch(
        framework_core::Window::new(
            "replays_the_recorded_greeting",
            framework_core::Size::new(800, 600),
        ),
        || support::Greeter::new(()),
    );
    app.replay(&recording).expect("the recording replays");
    assert_eq!(app.inspected_state(), recording.final_state);
}
