//! Typed messages from the project's catalogues (`PLAN.md` Milestone 46).
//!
//! `compile_messages()` reads `locales/<tag>.ftl`, checks the translations
//! against the source locale, and writes `OUT_DIR/messages.rs`:
//!
//! - `catalogues()`: every locale's file, embedded and parsed once — what
//!   the application hands to `Services::with_catalogues`;
//! - one function per message, taking exactly the message's variables.
//!   Numeric selectors (plurals) take `i64`, everything else
//!   `impl Into<String>`. A missing or extra argument is therefore a
//!   compile error, in a builder call and in a markup attribute alike.
//!
//! The source locale is `rustnative.toml`'s `[i18n] source` (default
//! `en`). A translation that reads a variable its source message does not
//! pass is an error; a message the source lacks, or one a translation
//! lacks, is a warning.
//!
//! The application declares the module with `framework_core::messages_mod!()`.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use framework_i18n::Bundle;

/// The project's source locale: `rustnative.toml`'s `[i18n] source`.
fn source_locale(project: &Path) -> String {
    std::fs::read_to_string(project.join("rustnative.toml"))
        .ok()
        .and_then(|text| text.parse::<toml::Table>().ok())
        .and_then(|table| table.get("i18n")?.get("source")?.as_str().map(str::to_owned))
        .unwrap_or_else(|| "en".to_owned())
}

/// A Rust identifier for message `id` (`inbox-count` → `inbox_count`).
fn function_name(id: &str) -> String {
    let name = id.replace('-', "_");
    if matches!(
        name.as_str(),
        "type"
            | "fn"
            | "match"
            | "mod"
            | "use"
            | "self"
            | "struct"
            | "loop"
            | "move"
            | "ref"
            | "static"
            | "super"
            | "trait"
            | "where"
            | "while"
            | "for"
            | "if"
            | "else"
            | "in"
            | "let"
            | "pub"
            | "return"
            | "impl"
            | "enum"
            | "crate"
            | "const"
            | "break"
            | "continue"
            | "as"
            | "extern"
            | "false"
            | "true"
            | "mut"
            | "unsafe"
            | "async"
            | "await"
            | "dyn"
    ) {
        format!("r#{name}")
    } else {
        name
    }
}

/// Checks the translations against the source; returns `(errors, warnings)`.
fn check(source: &str, bundles: &BTreeMap<String, Bundle>) -> (Vec<String>, Vec<String>) {
    let (mut errors, mut warnings) = (Vec::new(), Vec::new());
    let Some(reference) = bundles.get(source) else {
        errors.push(format!("there is no locales/{source}.ftl for the source locale `{source}`"));
        return (errors, warnings);
    };
    for (locale, bundle) in bundles.iter().filter(|(locale, _)| *locale != source) {
        for (id, message) in &bundle.messages {
            let Some(original) = reference.messages.get(id) else {
                warnings.push(format!(
                    "{locale}.ftl:{}: `{id}` is not in {source}.ftl; it is never shown",
                    message.line
                ));
                continue;
            };
            let passed = original.variables();
            for variable in message.variables().keys() {
                if !passed.contains_key(variable) {
                    errors.push(format!(
                        "{locale}.ftl:{}: `{id}` reads `${variable}`, which {source}.ftl's `{id}` is never given",
                        message.line
                    ));
                }
            }
        }
        for id in reference.messages.keys().filter(|id| !bundle.messages.contains_key(*id)) {
            warnings.push(format!("{locale}.ftl lacks `{id}`: the {source} text is shown"));
        }
    }
    (errors, warnings)
}

/// The generated module's text.
fn generate(
    source: &str,
    files: &[(String, PathBuf)],
    bundles: &BTreeMap<String, Bundle>,
) -> String {
    let mut out =
        String::from("// Generated by framework_build::compile_messages from locales/*.ftl.\n\n");
    let includes: Vec<String> = files
        .iter()
        .map(|(locale, path)| {
            format!("(\"{locale}\", include_str!({:?}))", path.display().to_string())
        })
        .collect();
    let _ = writeln!(
        out,
        "/// Every locale's catalogue, parsed once (checked when the application was built).
#[must_use]
pub fn catalogues() -> ::std::sync::Arc<::framework_core::i18n::Catalogues> {{
    static CATALOGUES: ::std::sync::OnceLock<::std::sync::Arc<::framework_core::i18n::Catalogues>> =
        ::std::sync::OnceLock::new();
    ::std::sync::Arc::clone(CATALOGUES.get_or_init(|| {{
        ::std::sync::Arc::new(
            ::framework_core::i18n::Catalogues::parse({source:?}, &[{}]).unwrap_or_default(),
        )
    }}))
}}
",
        includes.join(", ")
    );
    let Some(reference) = bundles.get(source) else { return out };
    for (id, message) in &reference.messages {
        let variables = message.variables();
        let parameters: Vec<String> = variables
            .iter()
            .map(|(name, numeric)| {
                let name = function_name(name);
                if *numeric { format!("{name}: i64") } else { format!("{name}: impl Into<String>") }
            })
            .collect();
        let arguments: String = variables
            .iter()
            .map(|(name, numeric)| {
                let parameter = function_name(name);
                if *numeric {
                    format!(".arg({name:?}, {parameter})")
                } else {
                    format!(".arg({name:?}, {parameter}.into())")
                }
            })
            .collect();
        let doc =
            message.comment.clone().unwrap_or_else(|| format!("`{id}` in locales/{source}.ftl."));
        for line in doc.lines() {
            let _ = writeln!(out, "/// {line}");
        }
        let _ = writeln!(
            out,
            "#[must_use]
pub fn {}({}) -> ::framework_core::i18n::Message {{
    ::framework_core::i18n::Message::new({id:?}){arguments}
}}
",
            function_name(id),
            parameters.join(", ")
        );
    }
    out
}

/// Reads `locales/*.ftl`, checks the translations, and writes
/// `OUT_DIR/messages.rs`. Run from a build script.
///
/// # Panics
///
/// When a catalogue does not parse, or a translation reads a variable its
/// source message is not given — the build fails with each problem.
pub fn compile_messages() {
    let project = std::env::var_os("CARGO_MANIFEST_DIR").map(PathBuf::from).unwrap_or_default();
    let out = std::env::var_os("OUT_DIR").map(PathBuf::from).unwrap_or_default();
    let locales = project.join("locales");
    println!("cargo:rerun-if-changed={}", locales.display());
    println!("cargo:rerun-if-changed=rustnative.toml");
    let source = source_locale(&project);
    let mut files = Vec::new();
    let mut bundles = BTreeMap::new();
    let mut errors = Vec::new();
    let mut entries: Vec<PathBuf> = std::fs::read_dir(&locales)
        .into_iter()
        .flatten()
        .flatten()
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|extension| extension == "ftl"))
        .collect();
    entries.sort();
    for path in entries {
        println!("cargo:rerun-if-changed={}", path.display());
        let locale =
            path.file_stem().map(|stem| stem.to_string_lossy().into_owned()).unwrap_or_default();
        let text = std::fs::read_to_string(&path)
            .unwrap_or_else(|cause| panic!("reading {}: {cause}", path.display()));
        match framework_i18n::parse(&text) {
            Ok(bundle) => {
                bundles.insert(locale.clone(), bundle);
            }
            Err(found) => errors.extend(
                found
                    .iter()
                    .map(|error| format!("{}:{}: {}", path.display(), error.line, error.message)),
            ),
        }
        files.push((locale, path));
    }
    let (checked, warnings) = check(&source, &bundles);
    errors.extend(checked);
    for warning in warnings {
        println!("cargo:warning={warning}");
    }
    assert!(errors.is_empty(), "the message catalogues do not compile:\n{}", errors.join("\n"));
    let generated = generate(&source, &files, &bundles);
    let target = out.join("messages.rs");
    if std::fs::read_to_string(&target).ok().as_deref() != Some(generated.as_str()) {
        std::fs::write(&target, generated)
            .unwrap_or_else(|cause| panic!("writing {}: {cause}", target.display()));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn bundles(files: &[(&str, &str)]) -> BTreeMap<String, Bundle> {
        files
            .iter()
            .map(|(locale, text)| ((*locale).to_owned(), framework_i18n::parse(text).unwrap()))
            .collect()
    }

    #[test]
    fn each_message_becomes_a_function_of_exactly_its_variables() {
        let bundles = bundles(&[(
            "en",
            "# The inbox button.\ninbox-count = { $count ->\n    [one] One\n   *[other] { $count }\n}\ninvited = { $gender ->\n    [feminine] { $name } (her)\n   *[other] { $name }\n}\ntype = Type\n",
        )]);
        let files = vec![("en".to_owned(), PathBuf::from("/p/locales/en.ftl"))];
        let code = generate("en", &files, &bundles);
        assert!(
            code.contains("/// The inbox button.\n#[must_use]\npub fn inbox_count(count: i64)"),
            "{code}"
        );
        assert!(
            code.contains("pub fn invited(gender: impl Into<String>, name: impl Into<String>)"),
            "{code}"
        );
        assert!(code.contains(".arg(\"gender\", gender.into()).arg(\"name\", name.into())"));
        assert!(code.contains("pub fn r#type()"), "a keyword is escaped");
        assert!(code.contains("include_str!(\"/p/locales/en.ftl\")"));
    }

    #[test]
    fn a_translation_that_reads_what_its_source_never_passes_is_an_error() {
        let bundles = bundles(&[
            ("en", "hello = Hello, { $name }\nbye = Bye\n"),
            ("pl", "hello = Cześć, { $nick }\nextra = Nadmiar\n"),
        ]);
        let (errors, warnings) = check("en", &bundles);
        assert_eq!(errors.len(), 1);
        assert!(errors[0].contains("`$nick`"), "{errors:?}");
        assert!(warnings.iter().any(|warning| warning.contains("`extra` is not in en.ftl")));
        assert!(warnings.iter().any(|warning| warning.contains("lacks `bye`")));
        let (errors, _) = check("fr", &bundles);
        assert!(errors[0].contains("no locales/fr.ftl"));
    }
}
